### PR TITLE
Increase dependency versions, Fix breaking changes in Cypress 5

### LINKED ISSUE #8: Add Cypress 5 support
The `Cypress.Cookies.defaults()` whitelist option has been renamed to `preserve` to more closely reflect its behavior. Addressed in [#7782](https://github.com/cypress-io/cypress/pull/7782).

The following code block would need to be updated:
https://github.com/sir-dunxalot/cypress-nextjs-auth0/blob/099dca6a43a0ef2d3d1fb6a6d7b79ea639f785dc/src/utils/whitelist-cookies.js#L1-L6

### PR DESCRIPTION
**Pull request by DevAtHeart**
Hi, I hope all is well, since I've seen that you haven't been active for a while.

This PR is basically for enabling usage with Cypress 5 (and 6 for that matter).

Closes #8.

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Thanks! LGTM. Merged and will release soon, perhaps *without* passing tests if I cannot soon solve the test suite issues identified in #6.

**Comment by sir-dunxalot** [comment]
Released with [1.0.0](https://github.com/sir-dunxalot/cypress-nextjs-auth0/releases/tag/1.0.0). Thanks again @DevAtHeart!

**Comment by DevAtHeart** [comment]
Thank you so much!

**Comment by cajimhe** [comment]
@sir-dunxalot I'm looking at the `/dist` folder of the freshly installed 1.0.0 and these fixes aren't there (still getting the `whitelist` error).

**Comment by sir-dunxalot** [comment]
@cajimhe Good catch! Perhaps the build command errored silently? I'll explore and will double-check `/dist` after release of a patch.

**Comment by sir-dunxalot** [comment]
This has been a weird rabbit hole but I believe `1.0.1` fixes the issue. The correct dist code is now deployed to NPM. For good measure, I've added a release command to this package to standardize the release process and catch errors.

@DevAtHeart @cajimhe @marklawlor I'd appreciate it if you can upgrade this module to `1.0.1` and confirm everything is working fine because I don't have an active project using this module *and* typescript. In other words, `1.0.1` released dist support for #6 that I am not easily able to test myself.

**Comment by cajimhe** [comment]
@sir-dunxalot seems to be working fine now. The whitelist error has gone and I could login with my credentials. Thanks dude :)

**Pull request merged**
