### PR TITLE
Add Typescript types

### LINKED ISSUE #3: Support typescript
Currently the `types` dir is empty. This addon should utilize typescript.

### PR DESCRIPTION
**Pull request by marklawlor**
Fixes #3

### CODE REVIEW

**Comment by marklawlor** [comment]
CI appears to be failing due to missing required environment variables

**Comment by sir-dunxalot** [comment]
Thanks @marklawlor! I'm looking into the CI issue. This repo has an unusual set up for Travis given the need for Auth0 secrets in the test suite so it's likely caused by that set up.

**Comment by sir-dunxalot** [comment]
I've had no luck fixing the CI suite yet. The issue appears to be with Travis secrets (previously correctly identified). Stay tuned!

**Comment by sir-dunxalot** [comment]
Tests are passing locally so I've released this with [1.0.0](https://github.com/sir-dunxalot/cypress-nextjs-auth0/releases/tag/1.0.0) will continue to investigate the Travis issues via #11.

**Pull request merged**
